#!/bin/bash
set -e
echo "Running init-db.sh..."

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_ROOT_USER}" <<-EOSQL
-- MERCHANT
CREATE USER "${MERCHANT_USER}" WITH ENCRYPTED PASSWORD '${MERCHANT_PASSWORD}';
CREATE DATABASE "${MERCHANT_DB}" OWNER "${MERCHANT_USER}";
GRANT ALL PRIVILEGES ON DATABASE "${MERCHANT_DB}" TO "${MERCHANT_USER}";

-- PROCESSING
CREATE USER "${PROCESSING_USER}" WITH ENCRYPTED PASSWORD '${PROCESSING_PASSWORD}';
CREATE DATABASE "${PROCESSING_DB}" OWNER "${PROCESSING_USER}";
GRANT ALL PRIVILEGES ON DATABASE "${PROCESSING_DB}" TO "${PROCESSING_USER}";
EOSQL

echo "Databases and users created successfully."
